import type { StudyCase } from './cases';

/** Set 2: each order is followed through delivery, payment and driver clearing until the job closes. */
export const CASES_2: StudyCase[] = [
  {
    title: 'มารับเอง ยังไม่จ่าย แล้วมาจ่ายเงินสดทีหลัง',
    level: 'พื้นฐาน',
    topics: ['มารับเอง', 'รับเงินทีหลัง', 'หน้าออเดอร์'],
    story: 'ลุงมาโนชมารับทรายถม 5 คิว บอกว่าจะเอาเงินสดมาจ่ายตอนบ่าย พอบ่ายลุงเอาเงินสดมาจ่ายครบ',
    source: 'pit',
    customer: { name: 'ทดสอบ21 ลุงมาโนช', phone: '0990000121', address: '3 ม.2 ต.ทุ่งฮั้ว' },
    items: [{ product: 'fill-sand', perTrip: 5, trips: 1 }],
    payment: 'cash',
    paidNow: false,
    after: [{ do: 'receive', method: 'cash' }],
  },
  {
    title: 'จัดส่ง จ่ายแล้ว คนขับยืนยันผ่านลิงก์',
    level: 'พื้นฐาน',
    topics: ['ลิงก์คนขับ', 'เคลียร์ค่ารถ', 'เงินสด'],
    story: 'คุณสมใจซื้อหินเล็กคละ 5 คิว จ่ายเงินสดที่ร้านแล้ว ให้อ้ายโกไปส่งตำบลวังแก้ว พอส่งถึงอ้ายโกกดยืนยันในลิงก์ สิ้นวันเคลียร์ค่ารถให้อ้ายโก',
    source: 'pit',
    customer: { name: 'ทดสอบ22 คุณสมใจ', phone: '0990000122', address: '15 ม.4 ต.วังแก้ว' },
    items: [{ product: 'small-stone', perTrip: 5, trips: 1 }],
    delivery: { zone: 'wang-kaeo', address: 'บ้านคุณสมใจ หลังวัด', driver: 'อ้ายโก' },
    payment: 'cash',
    after: [{ do: 'driverLink' }, { do: 'clearDriver' }],
  },
  {
    title: 'เก็บปลายทาง คนขับเก็บครบ หักค่ารถ',
    level: 'พื้นฐาน',
    topics: ['จ่ายปลายทาง', 'ลิงก์คนขับ', 'หักค่ารถ'],
    story:
      'คุณประยูรสั่งทรายก่อ/เท 10 คิว (2 เที่ยว) ส่งตำบลวังใต้ เก็บเงินปลายทาง สมศักดิ์ส่งครบ เก็บเงินได้ครบ แล้วกดยืนยันในลิงก์ ตอนเย็นสมศักดิ์เอาเงินมาส่งร้านโดยหักค่ารถของตัวเองไว้',
    source: 'pit',
    customer: { name: 'ทดสอบ23 คุณประยูร', phone: '0990000123', address: '40 ม.6 ต.วังใต้' },
    items: [{ product: 'mortar-sand', perTrip: 5, trips: 2 }],
    delivery: { zone: 'wang-tai', address: 'บ้านคุณประยูร ติดคลองส่งน้ำ', driver: 'สมศักดิ์' },
    payment: 'cod',
    after: [{ do: 'driverLink', cash: 'full' }, { do: 'clearDriver', mode: 'net' }],
  },
  {
    title: 'คนขับลืมกดลิงก์ ร้านกด "ส่งแล้ว" แทน',
    level: 'พื้นฐาน',
    topics: ['ร้านวัสดุ', 'สถานะจัดส่ง', 'รถ 3 คิว'],
    story:
      'ร้านวัสดุโอนค่าทรายถม 3 คิวมาแล้ว ให้แซมไปส่งตำบลทุ่งฮั้ว แซมโทรมาบอกว่าส่งแล้วแต่ไม่ได้กดลิงก์ ร้านจึงกด "ส่งแล้ว" ในหน้าออเดอร์เอง แล้วเคลียร์ค่ารถ',
    source: 'shop',
    customer: { name: 'ทดสอบ24 ร้านทุ่งฮั้ววัสดุ', phone: '0990000124', address: '7 ม.1 ต.ทุ่งฮั้ว' },
    items: [{ product: 'fill-sand', perTrip: 3, trips: 1 }],
    delivery: { zone: 'thung-hua', address: 'หน้างานลูกค้าร้าน ม.1 ซอย 2', driver: 'แซม' },
    payment: 'transfer',
    after: [{ do: 'shopDelivered' }, { do: 'clearDriver' }],
  },
  {
    title: 'ลูกค้าโอนหลังของถึง',
    level: 'พื้นฐาน',
    topics: ['โอนเงิน', 'ลิงก์คนขับ', 'รับเงินทีหลัง'],
    story:
      'คุณจิราสั่งหินคละใหญ่ 5 คิว ส่งตำบลวังเหนือ บอกว่าจะโอนเมื่อของถึง เทวาไปส่งแล้วกดยืนยันในลิงก์ (ไม่ต้องเก็บเงิน) จากนั้นคุณจิราโอนเงินมา แล้วเคลียร์ค่ารถให้เทวา',
    source: 'pit',
    customer: { name: 'ทดสอบ25 คุณจิรา', phone: '0990000125', address: '22 ม.3 ต.วังเหนือ' },
    items: [{ product: 'big-stone', perTrip: 5, trips: 1 }],
    delivery: { zone: 'wang-nuea', address: 'บ้านคุณจิรา รั้วสีขาว', driver: 'เทวา' },
    payment: 'transfer',
    paidNow: false,
    after: [{ do: 'driverLink' }, { do: 'receive', method: 'transfer' }, { do: 'clearDriver' }],
  },
  {
    title: 'เครดิต จัดส่ง ออกใบวางบิล จ่ายครบ',
    level: 'พื้นฐาน',
    topics: ['ร้านวัสดุ', 'เครดิต', 'ใบวางบิล'],
    story:
      'ร้านวัสดุสั่งหินเล็กคละ 10 คิว (2 เที่ยว) ส่งตำบลวังซ้าย ขอเครดิต โอ็ตไปส่งและกดยืนยันในลิงก์ สิ้นเดือนออกใบวางบิล ร้านโอนจ่ายครบ แล้วเคลียร์ค่ารถให้โอ็ต',
    source: 'shop',
    customer: { name: 'ทดสอบ26 ร้านวังซ้ายค้าวัสดุ', phone: '0990000126', address: '12 ม.5 ต.วังซ้าย' },
    items: [{ product: 'small-stone', perTrip: 5, trips: 2 }],
    delivery: { zone: 'wang-sai', address: 'หน้างานลูกค้าร้าน ม.5 ข้างโรงเรียน', driver: 'โอ็ต' },
    payment: 'credit',
    after: [
      { do: 'driverLink' },
      { do: 'statement' },
      { do: 'payStatement', amount: 'full', method: 'transfer' },
      { do: 'clearDriver' },
    ],
  },
  {
    title: 'เก็บปลายทาง คนขับเก็บเงินไม่ครบ',
    level: 'ปานกลาง',
    topics: ['จ่ายปลายทาง', 'ลิงก์คนขับ', 'เงินขาด'],
    story:
      'คุณเสาวลักษณ์สั่งทรายถม 5 คิว ส่งตำบลวังทรายคำ เก็บปลายทาง ลูกค้ามีเงินสดให้พ่อเลี้ยงตุ๋ยแค่ 2,000 บาท บอกว่าจะโอนส่วนที่เหลือทีหลัง พ่อเลี้ยงตุ๋ยแจ้งยอด 2,000 ในลิงก์',
    source: 'pit',
    customer: { name: 'ทดสอบ27 คุณเสาวลักษณ์', phone: '0990000127', address: '9 ม.8 ต.วังทรายคำ' },
    items: [{ product: 'fill-sand', perTrip: 5, trips: 1 }],
    delivery: { zone: 'wang-sai-kham', address: 'บ้านสวนคุณเสาวลักษณ์', driver: 'พ่อเลี้ยงตุ๋ย' },
    payment: 'cod',
    after: [{ do: 'driverLink', cash: 2000 }],
    expectBehaviour: [
      'หน้าเคลียร์ค่ารถยังนับ "เงินเก็บปลายทาง" เต็มยอดบิล ไม่ใช่ 2,000 ที่คนขับแจ้ง (ยังไม่ต้องกดเคลียร์ค่ารถ ให้จดว่าระบบแสดงยอดเท่าไร)',
    ],
  },
  {
    title: 'รับเงินปลายทางก่อน ค่ารถรอเคลียร์รอบเดือน',
    level: 'ปานกลาง',
    topics: ['จ่ายปลายทาง', 'เคลียร์ค่ารถรอบเดือน', 'รถ 3 คิว'],
    story:
      'ป้าสายใจสั่งทรายก่อ/เท 3 คิว ส่งตำบลวังแก้ว เก็บปลายทาง หลวงพูนเก็บเงินครบและกดยืนยัน ตอนเย็นหลวงพูนส่งเงินทั้งหมดให้ร้าน ค่ารถขอรับรวมสิ้นเดือน พอสิ้นเดือนร้านเคลียร์ค่ารถให้',
    source: 'pit',
    customer: { name: 'ทดสอบ28 ป้าสายใจ', phone: '0990000128', address: '31 ม.2 ต.วังแก้ว' },
    items: [{ product: 'mortar-sand', perTrip: 3, trips: 1 }],
    delivery: { zone: 'wang-kaeo', address: 'บ้านป้าสายใจ ซอยตรงข้ามร้านก๋วยเตี๋ยว', driver: 'หลวงพูน' },
    payment: 'cod',
    after: [{ do: 'driverLink', cash: 'full' }, { do: 'clearDriver', mode: 'later' }, { do: 'clearDriver' }],
  },
  {
    title: 'ค่ารถแพงกว่ายอดเก็บปลายทาง',
    level: 'ปานกลาง',
    topics: ['จ่ายปลายทาง', 'ร้านจ่ายค่ารถเพิ่ม', 'ขาดทุนค่าส่ง'],
    story:
      'คุณวีระสั่งทรายถมแค่ 2 คิว ส่งตำบลร่องเคาะ เก็บปลายทาง รถเล็กไม่ว่างต้องให้อ้ายเบล (รถ 5 คิว) ไปส่ง อ้ายเบลเก็บเงินครบและกดยืนยัน แล้วเคลียร์ค่ารถโดยหักจากเงินที่เก็บมา',
    source: 'pit',
    customer: { name: 'ทดสอบ29 คุณวีระ', phone: '0990000129', address: '5 ม.10 ต.ร่องเคาะ' },
    items: [{ product: 'fill-sand', perTrip: 2, trips: 1 }],
    delivery: { zone: 'rong-kho', address: 'บ้านคุณวีระ ปลายซอย', driver: 'อ้ายเบล' },
    payment: 'cod',
    tryFirst: ['ขั้นสินค้า: กด "อื่นๆ" แล้วพิมพ์ 2 คิว/เที่ยว จำนวน 1 เที่ยว'],
    after: [{ do: 'driverLink', cash: 'full' }, { do: 'clearDriver', mode: 'net' }],
    expectBehaviour: ['"คงเหลือเข้าร้าน" ในสรุปบิลต้องติดลบ และหน้าเคลียร์ค่ารถต้องขึ้น "ร้านจ่ายค่ารถเพิ่ม"'],
  },
  {
    title: 'ยกเลิกออเดอร์หลังส่งลิงก์ให้คนขับแล้ว',
    level: 'ปานกลาง',
    topics: ['ร้านวัสดุ', 'ยกเลิกออเดอร์', 'ลิงก์คนขับ'],
    story:
      'ร้านวัสดุสั่งหินเล็กคละ 3 คิว ส่งตำบลวังเหนือ เก็บปลายทาง ส่งลิงก์ให้ลุงช่วยแล้ว แต่ร้านโทรมายกเลิกก่อนรถออก ร้านจึงยกเลิกออเดอร์ แล้วให้ลองเปิดลิงก์ของคนขับดู',
    source: 'shop',
    customer: { name: 'ทดสอบ30 ร้านเหนือวัสดุ', phone: '0990000130', address: '18 ม.7 ต.วังเหนือ' },
    items: [{ product: 'small-stone', perTrip: 3, trips: 1 }],
    delivery: { zone: 'wang-nuea', address: 'หน้างานลูกค้าร้าน ม.7', driver: 'ลุงช่วย' },
    payment: 'cod',
    after: [{ do: 'cancel' }, { do: 'driverLink', cash: 'full' }],
    expectBehaviour: ['ออเดอร์ที่ยกเลิกต้องไม่ถูกนับในยอดรวมหน้าสรุปบิล และไม่ขึ้นในรายการเคลียร์ค่ารถ'],
  },
  {
    title: 'ยกเลิกผิดออเดอร์ แล้วกู้คืน',
    level: 'ปานกลาง',
    topics: ['ยกเลิกออเดอร์', 'กู้คืนออเดอร์', 'ตำบลไกล'],
    story:
      'คุณบุญเรือนโอนค่าทรายก่อ/เท 5 คิวมาแล้ว ส่งตำบลวังทอง ให้โอเว่นส่ง พนักงานกดยกเลิกออเดอร์นี้ผิด จึงกดกู้คืน จากนั้นโอเว่นไปส่งและกดยืนยัน แล้วเคลียร์ค่ารถ',
    source: 'pit',
    customer: { name: 'ทดสอบ31 คุณบุญเรือน', phone: '0990000131', address: '50 ม.4 ต.วังทอง' },
    items: [{ product: 'mortar-sand', perTrip: 5, trips: 1 }],
    delivery: { zone: 'wang-thong', address: 'บ้านคุณบุญเรือน ใกล้ อบต.วังทอง', driver: 'โอเว่น' },
    payment: 'transfer',
    after: [{ do: 'cancel' }, { do: 'restore' }, { do: 'driverLink' }, { do: 'clearDriver' }],
  },
  {
    title: 'กดรับเงินผิดช่องทาง แล้วแก้',
    level: 'ปานกลาง',
    topics: ['ร้านวัสดุ', 'มารับเอง', 'ยกเลิกการรับเงิน'],
    story:
      'ร้านวัสดุมารับหินคละใหญ่ 5 คิว บอกว่าจะโอน ตอนลูกค้าโอนมา พนักงานเผลอกด "รับเงินสด" จึงกด "ยกเลิกการรับเงิน" แล้วกด "รับโอนแล้ว" ใหม่ให้ถูก',
    source: 'shop',
    customer: { name: 'ทดสอบ32 ร้านศรีวังวัสดุ', phone: '0990000132', address: '27 ม.9 ต.วังซ้าย' },
    items: [{ product: 'big-stone', perTrip: 5, trips: 1 }],
    payment: 'transfer',
    paidNow: false,
    after: [{ do: 'receive', method: 'cash' }, { do: 'undoPay' }, { do: 'receive', method: 'transfer' }],
  },
  {
    title: 'ใบวางบิล รับชำระ 2 งวด',
    level: 'ปานกลาง',
    topics: ['ร้านวัสดุ', 'เครดิต', 'ใบวางบิล', 'รับชำระบางส่วน'],
    story:
      'ร้านวัสดุมารับเองทรายถม 10 คิว (2 เที่ยว) และหินเล็กคละ 5 คิว ขอเครดิต สิ้นเดือนออกใบวางบิล ร้านจ่ายเงินสดก่อน 3,000 บาท อีก 1 สัปดาห์โอนส่วนที่เหลือ',
    source: 'shop',
    customer: { name: 'ทดสอบ33 ร้านพูนผลวัสดุ', phone: '0990000133', address: '4 ม.3 ต.วังทอง' },
    items: [
      { product: 'fill-sand', perTrip: 5, trips: 2 },
      { product: 'small-stone', perTrip: 5, trips: 1 },
    ],
    payment: 'credit',
    after: [
      { do: 'statement' },
      { do: 'payStatement', amount: 3000, method: 'cash' },
      { do: 'payStatement', amount: 'full', method: 'transfer' },
    ],
  },
  {
    title: 'คนขับยืนยันแล้ว ร้านกดสถานะย้อนผิด',
    level: 'ปานกลาง',
    topics: ['สถานะจัดส่ง', 'ลิงก์คนขับ', 'ใครเป็นคนยืนยัน'],
    story:
      'คุณอำไพจ่ายเงินสดค่าทรายถม 5 คิวแล้ว ให้อาวชาติส่งตำบลวังซ้าย อาวชาติกดยืนยันในลิงก์แล้ว แต่พนักงานเผลอกด "กำลังจัดส่ง" ในหน้าออเดอร์ ให้ลองเปิดลิงก์คนขับดู แล้วร้านกด "ส่งแล้ว" คืน จากนั้นเคลียร์ค่ารถ',
    source: 'pit',
    customer: { name: 'ทดสอบ34 คุณอำไพ', phone: '0990000134', address: '16 ม.6 ต.วังซ้าย' },
    items: [{ product: 'fill-sand', perTrip: 5, trips: 1 }],
    delivery: { zone: 'wang-sai', address: 'บ้านคุณอำไพ ข้างศาลาประชาคม', driver: 'อาวชาติ' },
    payment: 'cash',
    after: [
      { do: 'driverLink' },
      { do: 'shopDispatched' },
      { do: 'driverLink' },
      { do: 'shopDelivered' },
      { do: 'clearDriver' },
    ],
  },
  {
    title: 'ยกเลิกออเดอร์ที่อยู่ในใบวางบิล',
    level: 'ท้าทาย',
    topics: ['ร้านวัสดุ', 'ใบวางบิล', 'ยกเลิกออเดอร์', 'ตรวจขอบเขต'],
    story:
      'ร้านวัสดุสั่งทรายก่อ/เท 3 คิว ส่งตำบลทุ่งฮั้ว ขอเครดิต ให้อินจันส่ง ออกใบวางบิลไปแล้ว ร้านโทรมายกเลิกเพราะยังไม่ได้ส่ง ให้ลองยกเลิกออเดอร์ก่อน ถ้าทำไม่ได้ให้ลบใบวางบิลแล้วยกเลิกใหม่',
    source: 'shop',
    customer: { name: 'ทดสอบ35 ร้านอินทร์วัสดุ', phone: '0990000135', address: '8 ม.4 ต.ทุ่งฮั้ว' },
    items: [{ product: 'mortar-sand', perTrip: 3, trips: 1 }],
    delivery: { zone: 'thung-hua', address: 'หน้างานลูกค้าร้าน ม.4 ทางเข้าไร่', driver: 'อินจัน' },
    payment: 'credit',
    after: [{ do: 'statement' }, { do: 'cancel' }, { do: 'deleteStatement' }, { do: 'cancel' }],
  },
  {
    title: 'คนขับแจ้งยังไม่ได้เงิน ลูกค้าโอนเข้าร้านเอง',
    level: 'ท้าทาย',
    topics: ['จ่ายปลายทาง', 'เงินขาด', 'ร้านจ่ายค่ารถ'],
    story:
      'คุณชาญสั่งหินเล็กคละ 6 คิว (2 เที่ยว เที่ยวละ 3 คิว) ส่งตำบลวังใต้ เก็บปลายทาง ให้หลวงพูนส่ง ลูกค้าไม่มีเงินสด หลวงพูนจึงแจ้งยอด 0 บาทในลิงก์ ต่อมาลูกค้าโอนเข้าบัญชีร้านเอง แล้วร้านจ่ายค่ารถให้หลวงพูน',
    source: 'pit',
    customer: { name: 'ทดสอบ36 คุณชาญ', phone: '0990000136', address: '61 ม.1 ต.วังใต้' },
    items: [{ product: 'small-stone', perTrip: 3, trips: 2 }],
    delivery: { zone: 'wang-tai', address: 'บ้านคุณชาญ ตรงข้ามปั๊มน้ำมัน', driver: 'หลวงพูน' },
    payment: 'cod',
    after: [{ do: 'driverLink', cash: 0 }, { do: 'receive', method: 'transfer' }, { do: 'clearDriver' }],
  },
  {
    title: 'รับเงินผ่านเคลียร์ค่ารถแล้ว ยกเลิกการรับเงินไม่ได้',
    level: 'ท้าทาย',
    topics: ['จ่ายปลายทาง', 'ลบรายการเคลียร์ค่ารถ', 'ตรวจขอบเขต'],
    story:
      'คุณสุรชัยสั่งทรายถม 10 คิว (2 เที่ยว) ส่งตำบลวังทอง เก็บปลายทาง โอ็ตเก็บครบและเคลียร์ค่ารถแบบหักค่ารถแล้ว ภายหลังพบว่าบันทึกผิด ให้ลองกด "ยกเลิกการรับเงิน" ในหน้าออเดอร์ก่อน จากนั้นให้ผู้ดูแลระบบ (super admin) ลบรายการเคลียร์ค่ารถ แล้วเคลียร์ใหม่',
    source: 'pit',
    customer: { name: 'ทดสอบ37 คุณสุรชัย', phone: '0990000137', address: '33 ม.5 ต.วังทอง' },
    items: [{ product: 'fill-sand', perTrip: 5, trips: 2 }],
    delivery: { zone: 'wang-thong', address: 'แปลงที่ดินคุณสุรชัย ริมถนนดำ', driver: 'โอ็ต' },
    payment: 'cod',
    after: [
      { do: 'driverLink', cash: 'full' },
      { do: 'clearDriver', mode: 'net' },
      { do: 'undoPay' },
      { do: 'deletePayout' },
      { do: 'clearDriver', mode: 'net' },
    ],
  },
  {
    title: 'คิวไม่เต็ม + ที่กันดาร + ลดค่าส่ง เก็บปลายทาง',
    level: 'ท้าทาย',
    topics: ['คิวต่อเที่ยว "อื่นๆ"', 'ที่กันดาร', 'ลดค่าส่ง', 'เคลียร์ค่ารถรอบเดือน'],
    story:
      'ลุงทองสั่งทรายก่อ/เท 5 คิว ส่งตำบลร่องเคาะบนดอย ทางแคบต้องใช้แซม (รถ 3 คิว) แบ่ง 2 เที่ยว เที่ยวละ 2.5 คิว บวกที่กันดาร 200 บาท ลุงขอลดค่าส่ง 100 บาท เก็บปลายทาง แซมเก็บครบ ส่งเงินให้ร้านทั้งหมด ค่ารถรอเคลียร์สิ้นเดือน',
    source: 'pit',
    customer: { name: 'ทดสอบ38 ลุงทอง', phone: '0990000138', address: '2 ม.12 ต.ร่องเคาะ' },
    items: [{ product: 'mortar-sand', perTrip: 2.5, trips: 2 }],
    delivery: { zone: 'rong-kho', address: 'บ้านลุงทอง บนดอย ทางลูกรัง', driver: 'แซม', remote: 200, deliveryDiscount: 100 },
    payment: 'cod',
    after: [{ do: 'driverLink', cash: 'full' }, { do: 'clearDriver', mode: 'later' }, { do: 'clearDriver' }],
  },
  {
    title: 'ใบวางบิล รับชำระผิด แล้วลบรายการรับชำระ',
    level: 'ท้าทาย',
    topics: ['ร้านวัสดุ', 'ใบวางบิล', 'ลบการรับชำระ', 'ตรวจขอบเขต'],
    story:
      'ร้านวัสดุสั่งหินคละใหญ่ 5 คิว ส่งตำบลวังแก้ว ขอเครดิต อ้ายเบลส่งและกดยืนยัน ออกใบวางบิลแล้ว พนักงานบันทึกรับเงินสด 1,000 บาทผิดใบ จึงลบรายการนั้น แล้วบันทึกรับโอนเต็มจำนวนให้ถูก จากนั้นเคลียร์ค่ารถ',
    source: 'shop',
    customer: { name: 'ทดสอบ39 ร้านแก้วมณีวัสดุ', phone: '0990000139', address: '11 ม.8 ต.วังแก้ว' },
    items: [{ product: 'big-stone', perTrip: 5, trips: 1 }],
    delivery: { zone: 'wang-kaeo', address: 'หน้างานลูกค้าร้าน ม.8 ใกล้หอถังประปา', driver: 'อ้ายเบล' },
    payment: 'credit',
    after: [
      { do: 'driverLink' },
      { do: 'statement' },
      { do: 'payStatement', amount: 1000, method: 'cash', tryFullAsPartial: true },
      { do: 'deleteStatementPayment' },
      { do: 'payStatement', amount: 'full', method: 'transfer' },
      { do: 'clearDriver' },
    ],
  },
  {
    title: 'บิลใหญ่ครบวงจร',
    level: 'ท้าทาย',
    topics: ['หลายสินค้า', 'ส่วนลดคิวละ', 'ส่วนลด %', 'จ่ายปลายทาง', 'หักค่ารถ'],
    story:
      'ผู้รับเหมาสั่งทรายถม 10 คิว (2 เที่ยว) ลดคิวละ 20 บาท และหินเล็กคละ 5 คิว (1 เที่ยว) ขอลดท้ายบิลอีก 5% ส่งตำบลวังทรายคำ เก็บปลายทาง สมศักดิ์ส่งครบ 3 เที่ยว เก็บเงินครบ แล้วเคลียร์ค่ารถแบบหักค่ารถ',
    source: 'pit',
    customer: { name: 'ทดสอบ40 หจก.ทดสอบมั่นคงก่อสร้าง', phone: '0990000140', address: '88 ม.2 ต.วังทรายคำ' },
    items: [
      { product: 'fill-sand', perTrip: 5, trips: 2, unitDiscount: 20 },
      { product: 'small-stone', perTrip: 5, trips: 1 },
    ],
    delivery: { zone: 'wang-sai-kham', address: 'โครงการโกดังสินค้า ม.2', driver: 'สมศักดิ์' },
    billDiscount: { type: 'percent', value: 5 },
    payment: 'cod',
    after: [{ do: 'driverLink', cash: 'full' }, { do: 'clearDriver', mode: 'net' }],
  },
];
