default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
      is_key_content_base64: true
    )

    increment_build_number(
      xcodeproj: "GoldenmoleDashboard.xcodeproj"
    )

    build_app(
      scheme: "GoldenmoleDashboard",
      project: "GoldenmoleDashboard.xcodeproj",
      export_method: "app-store",
      configuration: "Release"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
